Assignment4/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int PrimaryCategoryID { get; set; }
        public decimal Price { get; set; }
        public bool Active { get; set; }
        public string OtherAttributes { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}

Assignment4/Controllers/ProductsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Collections.Generic;
using System.Collections;
using Assignment4.Models;
using PagedList;
using System.Data.SqlClient;
namespace Assignment4.Controllers
{
    public class ProductsController : Controller
    {
        private IPTAssignment4Entities1 db = new IPTAssignment4Entities1();
        public static List<Product> prod = new List<Product>();
        // GET: Products
        public ActionResult Index(string searchOption, string searchQuery, int? page, string sortby)
        {
            //Sorting parameters
            ViewBag.SortByNameParameter = string.IsNullOrEmpty(sortby) ? "ProductName Sorting" : "";

            ViewBag.SortByPriceParameter = sortby == "ProductPrice" ? "ProductPrice Sorting" : "ProductPrice";

            //Product model.
            var product = db.Products.AsQueryable();
            
            //Searching.
            if (searchOption == "Category")
            {
                var catagoryId = db.Categories.Where(c => c.CategoryName.Equals(searchQuery));
                foreach (var cat in catagoryId)
                {
                    product = product.Where(pro => pro.PrimaryCategoryID.Equals(cat.CategoryId) || searchQuery == null).Include(pro => pro.Category);
                }
                prod = product.ToList();
            }
            else
            {
                if (searchOption == "Name")
                {
                    product= product.Where(p => p.ProductName.Contains(searchQuery) || searchQuery == null).Include(p => p.Category);
                    prod = product.ToList();
                }
                else
                {
                    if (searchOption == "Price")
                    {
                        int price = Convert.ToInt32(searchQuery);
                        product = product.Where(p => p.Price <= price || searchQuery == null);
                        prod = product.ToList();
                    }
                    else
                    {
                        if (searchOption == "Color")
                        {
                            
                            var pp = from p in db.Products.SqlQuery("select * from Product where OtherAttributes.exist('Product/OtherAttributes[@Color="+searchQuery+"]') = 1")
                                     select p;
                            product = pp.AsQueryable();
                            prod = product.ToList();

                        }
                        else
                        {
                            product = product.Where(p => p.ProductDescription.Contains(searchQuery) || searchQuery == null).Include(p => p.Category);
                            prod = product.ToList();
                        }
                    }
                    
                }

            }
            // Sorting 
            switch (sortby)
            {
                case "ProductName Sorting":
                    product = product.OrderByDescending(p => p.ProductName);
                    break;

                case "ProductPrice Sorting":
                    product = product.OrderByDescending(p => p.Price);
                    break;

                case "ProductPrice":
                    product = product.OrderBy(p => p.Price);
                    break;
                default:
                    product = product.OrderBy(p => p.ProductName);
                    break;
            }

            return View(product.ToPagedList(page ?? 1, 100));
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.PrimaryCategoryID = new SelectList(db.Categories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductName,ProductDescription,PrimaryCategoryID,Price,Active,OtherAttributes")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PrimaryCategoryID = new SelectList(db.Categories, "CategoryId", "CategoryName", product.PrimaryCategoryID);
            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.PrimaryCategoryID = new SelectList(db.Categories, "CategoryId", "CategoryName", product.PrimaryCategoryID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductName,ProductDescription,PrimaryCategoryID,Price,Active,OtherAttributes")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PrimaryCategoryID = new SelectList(db.Categories, "CategoryId", "CategoryName", product.PrimaryCategoryID);
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Export Summary Action Function.
        public ActionResult ExportSummary(int? page)
        {
            Dictionary<string, string> mylist = new Dictionary<string, string>();

            ViewBag.Total = db.Products.Count();
            foreach(var iterator in prod)
            {
                var categoryResult = db.Products.Count(m => m.Category.CategoryName == iterator.Category.CategoryName);
                var categorySearch = prod.Count(m => m.Category.CategoryName == iterator.Category.CategoryName);
                if(!mylist.ContainsKey(iterator.Category.CategoryName))
                mylist.Add(iterator.Category.CategoryName, categoryResult + "+" + categorySearch);
                ViewBag.List = mylist;      
            }
            return View("ExportSummary");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment4/Views/Products/Create.cshtml
@model Assignment4.Models.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimaryCategoryID, "PrimaryCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PrimaryCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PrimaryCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherAttributes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherAttributes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherAttributes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment4/Views/Products/Delete.cshtml
@model Assignment4.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherAttributes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherAttributes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Assignment4/Views/Products/Details.cshtml
@model Assignment4.Models.Product

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OtherAttributes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OtherAttributes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Assignment4/Views/Products/Edit.cshtml
@model Assignment4.Models.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PrimaryCategoryID, "PrimaryCategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PrimaryCategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PrimaryCategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OtherAttributes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OtherAttributes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OtherAttributes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Assignment4/Views/Products/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<Assignment4.Models.Product>

@{
    ViewBag.Title = "Index";
}

<br />
<div class="panel panel-default">
    <div class="panel-heading"><bold>Search Here </bold></div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <p>
                  @Html.ActionLink("Export", "ExportSummary", 1)
                    
                    @using (@Html.BeginForm("Index", "Products", FormMethod.Get))
            {
                        @Html.RadioButton("searchOption", "Name", true) <text><bold>Name &nbsp; </bold></text>

                        @Html.RadioButton("searchOption", "Price") <text><bold>Price &nbsp;</bold></text>

                        @Html.RadioButton("searchOption", "Category")<text><bold>Category &nbsp; </bold></text>

                        @Html.RadioButton("searchOption", "Color")<text><bold>Color </bold></text>

                        @Html.RadioButton("searchOption", "Description")<text><bold>Descriptions &nbsp;</bold></text>
                        <br />
                        @Html.TextBox("searchQuery")
                        <input type="submit" value="Search" />
}
</p>
            </div>

        </div>

    </div>
</div>






<p>
    @Html.ActionLink("Create New", "Create")
</p>
<br />
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Product Name  ", "Index", new { sortby = ViewBag.SortByNameParameter })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Active)
        </th>
        <th>
            @Html.ActionLink("Product Price  ", "Index", new { sortby = ViewBag.SortByPriceParameter })
        </th>
        <th> Color </th>
        <th> Size  </th>
        <th> Dimension </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Category.CategoryName)
        </th>
        <th> Actions </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            @if ((item.OtherAttributes) != null)
            {
                System.Xml.Linq.XElement xdoc = System.Xml.Linq.XElement.Parse(item.OtherAttributes);
                IEnumerable<System.Xml.Linq.XElement> ProductAttr = xdoc.Elements();
                var attributes = from attr in ProductAttr
                                 select attr;
                foreach (var attribute in attributes)
                {
                    <td>
                        @Html.DisplayFor(modelItem => attribute.Attribute("Color").Value)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => attribute.Attribute("Size").Value)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => attribute.Attribute("Dimension").Value)
                    </td>

                }

            }
            else
            {
                <td>-</td>
                <td>-</td>
                <td>-</td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
                
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ProductId }) |
                @Html.ActionLink("Details", "Details", new { id = item.ProductId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ProductId })
            </td>
        </tr>
    }

</table>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <p>Total  = @ViewBag.Total</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>



@Html.PagedListPager(Model, page => Url.Action("Index", new
{
    page,
    searchOption = Request.QueryString["searchOption"],
    searchQuery = Request.QueryString["searchQuery"]
}))